# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  project-build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
    - run: |
        zip -r target/site/serenity-report.zip target/site/serenity/
      if: always()
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-report
        path: target/site/serenity-report.zip